### ISSUE TITLE
How can i get the OG_node_state.txt?

### ISSUE THREAD

**Issue by pzx6** [IwasakiLab/Evodictor#1]
Now I have the genome of several species, the proteome file, how do I get this input.file?

**Comment by UTNK** [comment]
Hi @user6i, thank you for your question and sorry for my late reply.
You can prepare OG_node_state.txt by (1) ortholog annotation and (2) ancestral reconstruction, which is implemented in other software pipelines. For (1), you can use [KofamScan](https://academic.oup.com/bioinformatics/article/36/7/2251/5631907) or [EggNOG mapper](https://academic.oup.com/mbe/article/38/12/5825/6379734), for example. For (2), I recommend using [PastML](https://pastml.pasteur.fr/), or [castor](http://www.loucalab.com/archive/castor), for example. 
We used KofamScan and PastML for (1) and (2), respectively, in the [paper](https://www.science.org/doi/10.1126/sciadv.adc9130) presenting Evodictor (please also refer to Methods section for detail). Please feel free to ask me if you have other questions.

**Comment by pzx6** [comment]
Thank you very much for your reply, but I still have some questions. How did you obtain the orthologous genes of each species? Did you use the orthofinder tool to identify them?




皮球球
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IwasakiLab/Evodictor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IwasakiLab/Evodictor] How can i get the OG_node_state.txt? (Issue #1)





 
Hi @user6i, thank you for your question and sorry for my late reply.
 You can prepare OG_node_state.txt by (1) ortholog annotation and (2) ancestral reconstruction, which is implemented in other software pipelines. For (1), you can use KofamScan or EggNOG mapper, for example. For (2), I recommend using PastML, or castor, for example.
 We used KofamScan and PastML for (1) and (2), respectively, in the paper presenting Evodictor (please also refer to Methods section for detail). Please feel free to ask me if you have other questions.

**Comment by UTNK** [comment]
Thank you for your further question. In our paper, we used ortholog groups registered in [KEGG Orthology database](https://www.genome.jp/kegg/ko.html), so we did not define orthologs by ourselves using orthofinder or other tools. We used KofamScan to assign KEGG ortholog identifiers to every gene based on HMM profiles.

**Comment by pzx6** [comment]
Thanks, i have completed



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 13:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IwasakiLab/Evodictor] How can i get the OG_node_state.txt?(Issue #1)




 
Closed #1 as completed.
