### ISSUE TITLE
Input for PastML

### ISSUE THREAD

**Issue by sushanta26** [IwasakiLab/Evodictor#2]
Hi

Thank you for this amazing pipeline.

I am currently facing a challenge in determining the appropriate input for pastML to generate OG_node_state.txt. While I understand the use of kofam output, I am unsure about the process of creating OG_node_state.txt from a pastML run. Could you provide an example of a pastML input file that you have used to successfully generate OG_node_state.txt?

Thanks for the help

**Comment by UTNK** [comment]
Hi @sushanta26 

Thank you for your question.
I prepared `OG_node_state.txt` by reformatting the result files of PastML. I ran PastML for each ortholog and merged the PastML output files. Thus, I'm afraid that you cannot directly create `OG_node_state.txt` as the output file of PastML.

For the standard PastML input file format, please see the example data in https://pastml.pasteur.fr/
